services:
  # postgresql database
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwordlastsword
      POSTGRES_DB: greenseer_database
    ports:
      - "5432:5432" # maps ports
    volumes:
      - pgdata:/var/lib/postgresql/data # saves data

  # Backend
  backend:
    build: . # looks for build file
    ports:
      - "8080:8080" 
    environment:
      # connect db
      DATABASE_URL: postgres://admin:passwordlastsword@db:5432/greenseer_database
    depends_on:
      - db # database has to start before backend

# persistent storage
volumes:
  pgdata:
